HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc60d51bb70>: Failed to establish a new connection: [Errno 113] No route to host',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc60d51b208>: Failed to establish a new connection: [Errno 113] No route to host',))
1,"1/1/2018, 2:43:48 AM","1/1/2018, 2:55:50 AM",1,1.3,1,N,68,234,1,9,0.5,0.5,2.05,0,0.3,12.35,-,-

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc60d539780>: Failed to establish a new connection: [Errno 113] No route to host',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc60d529550>: Failed to establish a new connection: [Errno 113] No route to host',))


('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

