('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160ae500f0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b45c1d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b1dc9b0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
2,"1/1/2018, 2:53:56 AM","1/1/2018, 3:19:49 AM",2,2.91,1,N,142,68,1,18,0.5,0.5,3.86,0,0.3,23.16,-,-

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b443c50>: Failed to establish a new connection: [Errno 110] Connection timed out',))


HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160ae37c50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b45c3c8>: Failed to establish a new connection: [Errno 110] Connection timed out',))


HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b1e3d68>: Failed to establish a new connection: [Errno 110] Connection timed out',))
2,"1/1/2018, 2:57:01 AM","1/1/2018, 3:05:26 AM",3,1.35,1,N,74,41,2,7.5,0.5,0.5,0,0,0.3,8.8,-,-

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b1ef898>: Failed to establish a new connection: [Errno 110] Connection timed out',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b200ba8>: Failed to establish a new connection: [Errno 110] Connection timed out',))


HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b08f048>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160af93a90>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b09a908>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160af86d30>: Failed to establish a new connection: [Errno 110] Connection timed out',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b000630>: Failed to establish a new connection: [Errno 110] Connection timed out',))
2,"1/1/2018, 2:58:05 AM","1/1/2018, 3:14:37 AM",2,3.36,1,N,231,68,2,14,0.5,0.5,0,0,0.3,15.3,-,-


HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b00d0b8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b057668>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b041208>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b035160>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160adfa470>: Failed to establish a new connection: [Errno 110] Connection timed out',))

('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16085784a8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16085284a8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16085901d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608528828>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160854da58>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16085615c0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16084e8e10>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16084b4d30>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b475c18>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16084d91d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608465470>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16084ab940>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608479518>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608485198>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608491518>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160849da90>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608479b70>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608432048>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16084425c0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16084262b0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608432780>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160845a518>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16083e3198>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16083ed128>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160845abe0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160840f128>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608405240>: Failed to establish a new connection: [Errno 110] Connection timed out',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160841b6a0>: Failed to establish a new connection: [Errno 110] Connection timed out',))


('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16083f8240>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16083bec18>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16083c94e0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16083d3c50>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608368320>: Failed to establish a new connection: [Errno 110] Connection timed out',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16083b3f60>: Failed to establish a new connection: [Errno 110] Connection timed out',))

2,"1/1/2018, 2:31:42 AM","1/1/2018, 2:41:11 AM",1,1.41,1,N,211,87,1,8,0.5,0.5,1.86,0,0.3,11.16,-,-

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608360320>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608382cc0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608395470>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16083d33c8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608320198>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160833c2b0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b43bdd8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b45ccf8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b1dc828>: Failed to establish a new connection: [Errno 110] Connection timed out',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160af93198>: Failed to establish a new connection: [Errno 110] Connection timed out',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608395d30>: Failed to establish a new connection: [Errno 110] Connection timed out',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608395828>: Failed to establish a new connection: [Errno 110] Connection timed out',))


1,"1/1/2018, 2:57:00 AM","1/1/2018, 3:18:57 AM",1,3.6,1,N,236,107,1,16,0.5,0.5,4.3,0,0.3,21.6,-,-


HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160834ac18>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16083531d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
1,"1/1/2018, 2:59:57 AM","1/1/2018, 3:07:59 AM",1,1.7,1,N,50,239,1,7.5,0.5,0.5,1,0,0.3,9.8,-,-
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160834a710>: Failed to establish a new connection: [Errno 110] Connection timed out',))

2,"1/1/2018, 2:07:25 AM","1/1/2018, 2:12:01 AM",1,0.91,1,N,231,144,2,5.5,0.5,0.5,0,0,0.3,6.8,-,-

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160833c898>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160835ce80>: Failed to establish a new connection: [Errno 110] Connection timed out',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16083188d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))


HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16082afd30>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16082a2a58>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608301438>: Failed to establish a new connection: [Errno 110] Connection timed out',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16082afef0>: Failed to establish a new connection: [Errno 110] Connection timed out',))


HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160830ec50>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16082d77b8>: Failed to establish a new connection: [Errno 110] Connection timed out',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16082d7ef0>: Failed to establish a new connection: [Errno 110] Connection timed out',))


HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160826df98>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608276d30>: Failed to establish a new connection: [Errno 110] Connection timed out',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160b00dcf8>: Failed to establish a new connection: [Errno 110] Connection timed out',))


HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608296978>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160829f3c8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160822d4e0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608240080>: Failed to establish a new connection: [Errno 110] Connection timed out',))


HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160824c550>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608240390>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160817a0f0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160817ac88>: Failed to establish a new connection: [Errno 110] Connection timed out',))


HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16081865f8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160816edd8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160814e7b8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1608157b70>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f160815f1d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16080e91d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

