HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13dd030898>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13dcf13c50>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13dc225ac8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13dc152860>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13dc1a26d8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13dc393080>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13d474bc18>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13dc050080>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13dc179cc0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13d46bea58>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13d460f5f8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13dc082ac8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13dc196518>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13d46c8fd0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13d436f828>: Failed to establish a new connection: [Errno 110] Connection timed out',))

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13d4216cc0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
2,"1/1/2018, 2:53:46 AM","1/1/2018, 3:18:43 AM",4,1.77,1,N,161,164,2,15,0.5,0.5,0,0,0.3,16.3,-,-

HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13dc1e6c50>: Failed to establish a new connection: [Errno 110] Connection timed out',))

