HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033c0fb4a8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033c0ebb70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033c1076a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033c0eb198>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033c1149b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033c0fb5f8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033baaeba8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033babcbe0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033babc668>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033c107da0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033bd00ac8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033bd0e390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033bd0ec18>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033bd1c4e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033bd00c18>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033bd00160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033bfa38d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033bd1c4e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033bd1cd68>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033bd00be0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033bd0e320>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033bd0ec18>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033bd1cb00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
HTTPConnectionPool(host='cloud-server', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f033bd1c240>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
data is lost1
